wheezy:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=wheezybuild
    - TESTNODE=wheezytest
  links:
    - wheezybuild
    - wheezytest
    - rabbitmq
    - mongodb
    - postgres

jessie:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=jessiebuild
    - TESTNODE=jessietest
  links:
    - jessiebuild
    - jessietest
    - rabbitmq
    - mongodb
    - postgres

trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=trustybuild
    - TESTNODE=trustytest
  links:
    - trustybuild
    - trustytest
    - rabbitmq
    - mongodb
    - postgres

xenial:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest
    - rabbitmq
    - mongodb
    - postgres

el7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
    - ST2_GITURL=https://github.com/Plexxi/st2
    - ST2_GITREV=plexxi-v2.0.0
    - ST2PKG_RELEASE=3
    - ST2MISTRAL_GITURL=https://github.com/StackStorm/mistral
    - ST2MISTRAL_GITREV=st2-2.0.0
  links:
    - centos7build
    - centos7test
    - rabbitmq
    - mongodb
    - postgres

el6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
    - TESTNODE=centos6test
  links:
    - centos6build
    - centos6test
    - rabbitmq
    - mongodb
    - postgres

## Package build nodes
#
wheezybuild:
  image: quay.io/stackstorm/packagingenv:wheezy
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

jessiebuild:
  image: quay.io/stackstorm/packagingenv:jessie
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

trustybuild:
  image: quay.io/stackstorm/packagingenv:trusty
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

xenialbuild:
  image: stackstorm/packagingenv:xenial
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

centos6build:
  image: quay.io/stackstorm/packagingenv:centos6
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos7build:
  image: quay.io/stackstorm/packagingenv:centos7
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

## Package testing nodes
#
wheezytest:
  image: quay.io/dennybaa/droneunit:wheezy-sshd
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

jessietest:
  image: quay.io/dennybaa/droneunit:jessie-sshd
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

trustytest:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

xenialtest:
  image: stackstorm/packagingtest:xenial
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-circle
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos6test:
  image: quay.io/dennybaa/droneunit:centos6-sshd
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos7test:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
